export const DEVNET_COUNTER_PACKAGE_ID = "0xTODO";
export const TESTNET_COUNTER_PACKAGE_ID = "0xTODO";
export const MAINNET_COUNTER_PACKAGE_ID = "0xTODO";

export const DEVNET_MINTER_PACKAGE_ID = "0x3744f8000a921c155375bd130e3bb3a758f2ed8fd48c324325f46cdce642cf91";
export const TESTNET_MINTER_PACKAGE_ID = "0xTODO";
export const MAINNET_MINTER_PACKAGE_ID = "0xTODO";

export const DEVNET_COLLECTION_PACKAGE_ID = "0xTODO";
export const TESTNET_COLLECTION_PACKAGE_ID = "0xTODO";
export const MAINNET_COLLECTION_PACKAGE_ID = "0xTODO";
