export const DEVNET_COUNTER_PACKAGE_ID = "0xTODO";
export const MAINNET_COUNTER_PACKAGE_ID = "0xTODO";
export const DEVNET_MINTER_PACKAGE_ID = "0xTODO";
export const MAINNET_MINTER_PACKAGE_ID = "0xTODO";
